GiganticMinecraft/seichi-portal-backend

- .github/workflows/ci.yml
> ci: fix target dir path

- server/form/src/domain/models.rs
- server/form/src/infrastructure/form_persistence.rs
> refactor: fix fetch_forms

- rust-toolchain.toml
As you can see, literally literally.
> feat: pin channel in rust-toolchain.toml

- server/Cargo.lock
- server/app/Cargo.toml
- server/app/src/config.rs
- server/app/src/main.rs
- server/database/Cargo.toml
- server/database/src/config.rs
- server/database/src/connection.rs
- server/database/src/lib.rs
環境変数などの設定がコードベースでも一箇所にまとまっていたほうが変更や追加があったときに強いのでは説
> feat: aggregates config variables into some structs

- .github/workflows/build-and-release-application.yaml
- compose.yaml
> buf-setup-actionにtokenを仕込む

- .cargo-husky/hooks/pre-commit
> chore: cargo fmt on pre-commit

- server/Makefile.common.toml
- server/app/Makefile.toml
- server/database/Makefile.toml
- server/errors/Makefile.toml
- server/form/Makefile.toml
- server/migration/Makefile.toml
[cargo-make](https://github.com/sagiegurari/cargo-make) を使ってタスクを実行できるようにしておいた
> chore: cargo-make the task runner

- README.md
開発環境が限定されていない README なのでポータブルなシェルスクリプトにした
> feat(docs): powershellでも動くくらいポータブルなスクリプトに

- server/Cargo.lock
- server/Cargo.toml
- server/common/Cargo.toml
- server/common/Makefile.toml
- server/common/src/lib.rs
- server/common/src/test_utils.rs
- server/domain/Cargo.toml
- server/domain/src/form/models.rs
- server/errors/Cargo.toml
- server/errors/Makefile.toml
- server/errors/src/domain.rs
- server/errors/src/lib.rs
- server/infra/resource/src/database/form.rs
- server/presentation/Cargo.toml
- server/presentation/src/form_handler.rs
- test-case によるテストの例を追加（domain）
- proptest によるテストの設定（domain, common）
- strum による enum <-> String の変換と DomainError の建設 (domain, errors)
> feat: テストできるようにした

- .github/workflows/audit.yaml
> chroe(ci): add audit.yaml

- server/Cargo.lock
- server/entrypoint/src/main.rs
- server/presentation/src/health_check_handler.rs
- server/presentation/src/lib.rs
とりあえずポイントを用意するだけなので、それ以外特に何もしてないです
> feat: healthCheckを実装する

- .github/workflows/image-release.yaml
> fix(ci): master => main

- compose.yaml
> MYSQL_ROOT_PASSWORDをenvironmentに追記

- server/domain/src/form/models.rs
- server/infra/entities/src/sea_orm_active_enums.rs
- server/migration/src/m20221211_211233_form_questions.rs
> QuestionTypeでUI上の語句を持たせない

- server/domain/src/form/models.rs
- server/domain/src/repository/form_repository.rs
- server/infra/entities/src/form_meta_data.rs
- server/infra/resource/src/database/components.rs
- server/infra/resource/src/database/form.rs
- server/infra/resource/src/repository/form_repository_impl.rs
- server/presentation/src/form_handler.rs
- server/usecase/src/create_form.rs
> FormNameではなく、FormTitleに統一する

- CONTRIBUTING.md
新たに定義された以下のcargo-makeタスクをドキュメントに記載しました。
- generate-entity
- generate-migrate-file
> cargo-makeで新たに定義されたタスクをドキュメントに記載

- server/presentation/src/form_handler.rs
> feat: content-type/json

- server/domain/src/form/models.rs
- server/domain/src/repository/form_repository.rs
- server/infra/resource/src/database/components.rs
- server/infra/resource/src/database/form.rs
- server/infra/resource/src/repository/form_repository_impl.rs
- server/presentation/src/form_handler.rs
- server/usecase/src/form.rs
フォーム作成時に`description`が受け取れていなかった
> フォームの説明が保存されない不具合を修正

- server/entrypoint/Cargo.toml
ref. https://docs.sentry.io/platforms/rust/profiling/#enable-profiling
> enable profiling feature

- server/Cargo.lock
- server/entrypoint/Cargo.toml
- server/entrypoint/src/main.rs
- server/infra/outgoing/Cargo.toml
- server/infra/outgoing/src/form_outgoing.rs
- server/infra/outgoing/src/webhook.rs
- server/infra/resource/Cargo.toml
- server/infra/resource/src/database/connection.rs
- server/infra/resource/src/database/form.rs
- server/infra/resource/src/repository.rs
- server/infra/resource/src/repository/form_repository_impl.rs
ref: https://github.com/GiganticMinecraft/seichi-timed-stats-conifers/blob/eebb4cf95e85591d3664ab37a78f01e13f4a7927/server/ingestor/src/main.rs#L70-L79
> tracing::instrumentをつける

- server/Cargo.lock
- server/Cargo.toml
- server/domain/Cargo.toml
- server/entrypoint/Cargo.toml
- server/infra/resource/src/repository.rs
- server/infra/resource/src/repository/form_repository_impl.rs
こうすればいいですよ、コンパイラの言うことに従えばいいってもんじゃない、実はね。
> fix: tracing::instrument(skip(self))

- .github/workflows/ci.yaml
- .github/workflows/image-release.yaml
- rust-toolchain.toml
[Announcing Rust 1.71.0](https://blog.rust-lang.org/2023/07/13/Rust-1.71.0.html)
> chore: Announcing Rust 1.71.0

- server/domain/src/form/models.rs
- server/infra/entities/src/form_questions.rs
- server/infra/resource/src/database/form.rs
- server/infra/resource/src/dto.rs
- server/migration/src/m20221211_211233_form_questions.rs
> feat: questionにis_requiredオプションを追加

- server/Cargo.lock
- server/Cargo.toml
- server/domain/src/form/models.rs
- server/domain/src/repository/form_repository.rs
- server/infra/resource/Cargo.toml
- server/infra/resource/src/database/components.rs
- server/infra/resource/src/database/form.rs
- server/infra/resource/src/repository/form_repository_impl.rs
- server/presentation/src/form_handler.rs
- server/usecase/src/form.rs
LimitとOffsetの指定は必須ではないのでOptionをつけて任意指定にしました
> feat: フォーム一覧を取得するエントリポイントの`Offset`と`Limit`の指定を任意にする

- server/domain/src/form/models.rs
- server/domain/src/repository/form_repository.rs
- server/entrypoint/src/main.rs
- server/infra/resource/src/database/components.rs
- server/infra/resource/src/database/form.rs
- server/infra/resource/src/repository/form_repository_impl.rs
- server/presentation/src/form_handler.rs
- server/usecase/src/form.rs
> 質問を作成するエントリポイントの実装

- server/entrypoint/src/main.rs
- server/infra/resource/src/database/form.rs
- fix: 選択肢を追加するコードが動いていなかったので修正
- fix: add equal for range
> 質問の選択肢が追加できないのを修正

- .github/workflows/ci.yaml
- .github/workflows/image-release.yaml
- rust-toolchain.toml
- server/Cargo.toml
https://blog.rust-lang.org/2023/08/24/Rust-1.72.0.html
> feat: Annoucing Rust 1.72.0

- server/infra/resource/src/database/form.rs
> fix: question_typeがTEXTでも選択肢が挿入できてしまうのを修正

- server/presentation/src/form_handler.rs
> fix: 質問の追加が成功した場合に201を返すようにする

- server/domain/src/form/models.rs
- server/domain/src/repository/form_repository.rs
- server/infra/resource/src/database/components.rs
- server/infra/resource/src/database/form.rs
- server/infra/resource/src/dto.rs
- server/infra/resource/src/repository/form_repository_impl.rs
- server/usecase/src/form.rs
`/forms`に対する`GET`リクエストで返ってくるのはフォームの最低限の情報だけなので、それに合わせる
> /formsにGETをしたときのレスポンスをAPI定義に合わせる

- server/domain/src/form/models.rs
- server/migration/src/m20220101_000001_create_table.rs
> フォームの公開設定のデフォルトをPRIVATEにする

- server/infra/resource/src/database/form.rs
UUIDに直接変換できなかったのでStringを取得してから変換するように変更
> 回答の取得をするエンドポイントでUUIDのデコードが失敗するのを修正

- server/presentation/src/auth.rs
> 自身のユーザー情報を取得するエンドポイントに権限がないユーザーがアクセスできないのを修正

- server/Cargo.lock
- server/entrypoint/Cargo.toml
- server/entrypoint/src/main.rs
> feat: 存在しないエンドポイントにアクセスされた場合のハンドラを追加

- server/domain/src/form/models.rs
- server/infra/resource/src/database/form.rs
回答可能期間が変更できない不具合と、`webhook`が指定されていないとエラーになるのを修正しました
> フォームの一部設定が変更できないのを修正

- server/Cargo.lock
- server/domain/src/form/models.rs
- server/domain/src/repository/form_repository.rs
- server/infra/resource/src/database/components.rs
- server/infra/resource/src/database/form.rs
- server/infra/resource/src/dto.rs
- server/infra/resource/src/repository/form_repository_impl.rs
- server/presentation/src/form_handler.rs
- server/types/Cargo.toml
- server/types/src/lib.rs
- server/usecase/src/form.rs
IDから元になっているもの(今回で言えば`AnswerId`から`PostedAnswers`)を取得できる関数を実装しました。
> IDから元になっているものを取得できる関数の実装

- server/Cargo.lock
- server/domain/src/form/models.rs
- server/domain/src/repository/form_repository.rs
- server/errors/src/infra.rs
- server/infra/outgoing/Cargo.toml
- server/infra/outgoing/src/form_outgoing.rs
- server/infra/outgoing/src/webhook.rs
- server/infra/resource/Cargo.toml
- server/infra/resource/src/database/components.rs
- server/infra/resource/src/database/form.rs
- server/infra/resource/src/dto.rs
- server/infra/resource/src/repository/form_repository_impl.rs
- server/presentation/src/form_handler.rs
- server/types/Cargo.toml
- server/types/src/lib.rs
- server/usecase/src/form.rs
#371 が前提になっているPRなので、先に #371 をマージしてほしいです
> 回答が投稿されたときとコメントが投稿されたときのwebhook連携を追加

- server/Cargo.lock
- server/domain/src/form/models.rs
- server/domain/src/repository/form_repository.rs
- server/infra/resource/src/database/components.rs
- server/infra/resource/src/database/form.rs
- server/infra/resource/src/dto.rs
- server/infra/resource/src/repository/form_repository_impl.rs
- server/presentation/src/form_handler.rs
- server/types/Cargo.toml
- server/types/src/lib.rs
- server/usecase/Cargo.toml
- server/usecase/src/form.rs
https://github.com/GiganticMinecraft/seichi-portal-backend/pull/371 が前提になっているPRなので、先に https://github.com/GiganticMinecraft/seichi-portal-backend/pull/371 をマージしてほしいです
> フォームの回答可能期間を考慮する

- .github/workflows/ci.yaml
- .github/workflows/image-release.yaml
- rust-toolchain.toml
- server/Cargo.lock
[Announcing Rust 1.75.0](https://blog.rust-lang.org/2023/12/28/Rust-1.75.0.html)
特に、https://blog.rust-lang.org/2023/12/21/async-fn-rpit-in-traits.html を読むこと
> Feature/announcing rust 1.75.0

- server/domain/src/repository/user_repository.rs
- server/domain/src/user/models.rs
- server/errors/src/infra.rs
- server/infra/resource/src/database/components.rs
- server/infra/resource/src/database/user.rs
- server/infra/resource/src/repository/user_repository_impl.rs
- server/presentation/src/auth.rs
- server/usecase/src/user.rs
そもそもデータベースから取得する処理が書かれていなかったので書きました
> ユーザー権限が管理者のときに権限情報が取得できないのを修正

- server/domain/src/form/models.rs
- server/domain/src/repository/form_repository.rs
- server/infra/resource/src/database/components.rs
- server/infra/resource/src/database/form.rs
- server/infra/resource/src/repository/form_repository_impl.rs
- server/presentation/src/form_handler.rs
- server/usecase/src/form.rs
スキーマ上では作成した質問に紐づくフォームのIDを返すことになっていた
> 質問を作成したときのレスポンスが間違っていたので修正

- server/domain/src/form/models.rs
> fix: update_at -> updated_at

- server/domain/src/repository/form_repository.rs
- server/entrypoint/src/main.rs
- server/infra/resource/src/database/components.rs
- server/infra/resource/src/database/form.rs
- server/infra/resource/src/repository/form_repository_impl.rs
- server/presentation/src/form_handler.rs
- server/usecase/src/form.rs
> feat: 質問を上書きするエンドポイントの実装

- .github/workflows/ci.yaml
> sccacheのインストールで使用するactionを変更

- server/Cargo.lock
- server/entrypoint/src/main.rs
- server/errors/src/usecase.rs
- server/presentation/src/form_handler.rs
- server/usecase/src/form.rs
回答を ID を指定して取得するエンドポイントの実装を行いました。
#469 を マージ -> リベース してからこの PR をマージしてほしいです。
> 回答を ID を指定して取得するエンドポイントの実装

- server/domain/src/form/models.rs
- server/domain/src/repository/form_repository.rs
- server/entrypoint/src/main.rs
- server/infra/resource/src/database/components.rs
- server/infra/resource/src/database/form.rs
- server/infra/resource/src/repository/form_repository_impl.rs
- server/presentation/src/form_handler.rs
- server/usecase/src/form.rs
#483 を先にマージして、このブランチをリベースしてからマージしてほしいです
> 回答のメタデータを更新するエンドポイントの実装

- server/domain/src/form/models.rs
- server/domain/src/repository/form_repository.rs
- server/infra/resource/src/database/components.rs
- server/infra/resource/src/database/form.rs
- server/infra/resource/src/dto.rs
- server/infra/resource/src/repository/form_repository_impl.rs
- server/presentation/src/form_handler.rs
- server/usecase/src/form.rs
質問への回答を返すときはその回答に紐づけられたコメントも返すように実装しました。
#508 を先にマージしてからマージしてほしいです
> 質問への回答を返すときに回答に対するコメントも含めて返すようにする

- server/domain/src/form/models.rs
- server/domain/src/repository/form_repository.rs
- server/entrypoint/src/main.rs
- server/infra/resource/src/database/components.rs
- server/infra/resource/src/database/form.rs
- server/infra/resource/src/repository/form_repository_impl.rs
- server/migration/src/m20220101_000001_create_table.rs
- server/presentation/src/form_handler.rs
- server/usecase/src/form.rs
https://github.com/GiganticMinecraft/seichi-portal-backend/pull/511 を先にマージしてからリベースしてマージしてほしいです
> フォームに来た回答に対してつけられるラベルを作成するエンドポイントを実装

- server/infra/resource/src/database/connection.rs
- server/infra/resource/src/database/form.rs
以下の問題を修正しました
・質問の削除ができない
・質問の選択肢が増殖する
> 質問をputするエンドポイントの不具合を修正

- server/domain/src/repository/form_repository.rs
- server/entrypoint/src/main.rs
- server/infra/resource/src/database/components.rs
- server/infra/resource/src/database/form.rs
- server/infra/resource/src/repository/form_repository_impl.rs
- server/presentation/src/form_handler.rs
- server/usecase/src/form.rs
> 回答につけられるラベルの操作をするエンドポイントの実装

- .github/workflows/audit.yaml
> SecurityAuditが正常に作動していないのを修正

- server/domain/src/search/models.rs
- server/entrypoint/src/main.rs
- server/presentation/src/search_handler.rs
- server/usecase/src/search.rs
> chore: full_search -> cross_search

- server/domain/src/form/models.rs
- server/domain/src/repository/form_repository.rs
- server/infra/resource/src/database/components.rs
- server/infra/resource/src/database/form.rs
- server/infra/resource/src/repository/form_repository_impl.rs
- server/usecase/src/form.rs
`InfraError` として NotFound 系のエラーを返すべきではない(`Option` にして返すべき)だと思ったので取り除こうとしましたが、思ったより根深かったので一部だけ
> refactor: infra-error から FormNotFound を取り除こうとした

- server/domain/src/types/authorization_guard.rs
`AuthorizationGuard` の `try_into_read` 関数と `try_read` 関数から取得したデータが等しいこと確認するテストを追加
> test: AuthorizationGuardのテストを追加

- server/Cargo.lock
- server/Cargo.toml
- server/entrypoint/Cargo.toml
- server/errors/Cargo.toml
- server/migration/Cargo.toml
axum-extra は 1.11.0 が yanked になっていたのでダウングレード
> 依存クレートのバージョンを更新

- server/entrypoint/src/main.rs
https://github.com/tokio-rs/axum/releases/tag/axum-v0.8.0 によると指定方法が変わったので
> fix: path parameter の指定を :id から {id} に変更

- server/presentation/src/auth.rs
`AuthorizationGuardWithContext` で認可情報を定義できるようになったので、ここで定義する必要がなくなった
> fix: auth handler からユーザーがアクセスできるエンドポイントの定義を削除

- .github/workflows/ci.yaml
- .github/workflows/image-release.yaml
> feat(actions): set rust version from rust-toolchain.toml

- .github/workflows/image-release.yaml
actions-rs/toolchain is now public archived
> fix(actions): use dtolnay/rust-toolchain instead of actions-rs/toolchain

- server/Cargo.lock
- server/Cargo.toml
- server/common/Cargo.toml
- server/common/src/config.rs
- server/infra/resource/Cargo.toml
- server/infra/resource/src/database/config.rs
> refactor: once_cell から LazyLock に切り替える

- server/domain/src/form/service.rs
> feat: 回答のタイトルに回答者名を埋め込める機能の実装

- .github/workflows/ci.yaml
> ci: CI の改善

- server/Cargo.lock
- server/domain/Cargo.toml
- server/domain/src/notification.rs
- server/domain/src/notification/discord_sender.rs
- server/domain/src/notification/models.rs
- server/domain/src/repository/notification_repository.rs
- server/domain/src/user/models.rs
- server/entrypoint/src/main.rs
- server/errors/src/usecase.rs
- server/infra/resource/src/database/components.rs
- server/infra/resource/src/database/notification.rs
- server/infra/resource/src/dto.rs
- server/infra/resource/src/outgoing.rs
- server/infra/resource/src/outgoing/discord_sender_impl.rs
- server/infra/resource/src/repository/notification_repository_impl.rs
- server/migration/src/m20220101_000001_create_table.rs
- server/presentation/src/handlers/error_handler.rs
- server/presentation/src/handlers/notification_handler.rs
- server/presentation/src/schemas/notification/notification_request_schemas.rs
- server/presentation/src/schemas/notification/notification_response_schemas.rs
- server/usecase/src/forms/message.rs
- server/usecase/src/notification.rs
> Discord への通知設定を実装

- server/domain/src/notification/models.rs
- server/domain/src/repository/notification_repository.rs
- server/entrypoint/src/main.rs
- server/infra/resource/src/database/components.rs
- server/infra/resource/src/database/notification.rs
- server/infra/resource/src/dto.rs
- server/infra/resource/src/repository/notification_repository_impl.rs
- server/migration/src/m20220101_000001_create_table.rs
- server/presentation/src/handlers/notification_handler.rs
- server/presentation/src/schemas/notification/notification_request_schemas.rs
- server/presentation/src/schemas/notification/notification_response_schemas.rs
- server/usecase/src/notification.rs
> refactor: 既存の通知機能を削除

- server/entrypoint/src/main.rs
- server/presentation/src/handlers/user_handler.rs
- server/usecase/src/user.rs
> feat: 連携済みの discord アカウントを取得するエンドポイントの実装

- server/domain/src/form/answer/settings/models.rs
- server/domain/src/form/models.rs
- server/domain/src/repository/form/form_repository.rs
- server/infra/resource/src/database/components.rs
- server/infra/resource/src/database/forms/form.rs
- server/infra/resource/src/repository/form_repository_impls/form_repository_impl.rs
- server/presentation/src/handlers/form/form_handler.rs
- server/presentation/src/schemas/form/form_request_schemas.rs
- server/usecase/src/forms/form.rs
> フォームのデータ操作に AuthorizationGuard を用いる

- server/domain/src/repository/user_repository.rs
- server/domain/src/user/models.rs
- server/infra/resource/src/database/notification.rs
- server/infra/resource/src/repository/user_repository_impl.rs
- server/migration/src/m20220101_000001_create_table.rs
- server/presentation/src/auth.rs
- server/presentation/src/handlers/user_handler.rs
- server/usecase/src/forms/message.rs
- server/usecase/src/notification.rs
- server/usecase/src/user.rs
> ユーザー操作に対する認可操作を実装

- server/Cargo.lock
- server/domain/Cargo.toml
- server/domain/src/form/answer/models.rs
- server/domain/src/form/answer/service.rs
- server/domain/src/form/message.rs
- server/domain/src/form/message/models.rs
- server/domain/src/form/message/service.rs
- server/domain/src/repository/form/answer_repository.rs
- server/domain/src/repository/form/message_repository.rs
- server/infra/resource/src/database/components.rs
- server/infra/resource/src/database/forms/answers.rs
- server/infra/resource/src/database/forms/message.rs
- server/infra/resource/src/dto.rs
- server/infra/resource/src/repository/form_repository_impls/answer_repository_impl.rs
- server/infra/resource/src/repository/form_repository_impls/message_repository_impl.rs
- server/presentation/src/handlers/form/answer_handler.rs
- server/presentation/src/handlers/form/message_handler.rs
- server/presentation/src/schemas/form/form_response_schemas.rs
- server/usecase/src/dto.rs
- server/usecase/src/forms/answer.rs
- server/usecase/src/forms/message.rs
> refactor: answer モデルの集約単位を変更

- server/Cargo.lock
- server/Cargo.toml
- server/migration/Cargo.toml
Cargo.lock だけ更新されるようになってしまったので作り直す
> chore: re-create-cargo.logk

- .cargo-husky/hooks/pre-commit
- .cargo-husky/hooks/rustfmt.toml
- .github/workflows/ci.yaml
- server/Makefile.toml
- server/presentation/src/handlers/form/message_handler.rs
> 使用するフォーマッターを stable に統一する

- server/domain/src/repository/search_repository.rs
- server/domain/src/search/models.rs
- server/infra/resource/src/database/components.rs
- server/infra/resource/src/database/forms/answers.rs
- server/infra/resource/src/database/search.rs
- server/infra/resource/src/repository/search_repository_impl.rs
- server/presentation/src/schemas/search_schemas.rs
- server/usecase/src/dto.rs
- server/usecase/src/search.rs
> fix: 回答の検索時に認可処理が行われていないのを修正

- server/migration/src/m20220101_000001_create_table.rs
- server/presentation/src/auth.rs
- server/presentation/src/handlers/error_handler.rs
- server/presentation/src/handlers/form/answer_handler.rs
- server/presentation/src/handlers/form/answer_label_handler.rs
- server/presentation/src/handlers/form/comment_handler.rs
- server/presentation/src/handlers/form/form_handler.rs
- server/presentation/src/handlers/form/form_label_handler.rs
- server/presentation/src/handlers/form/message_handler.rs
- server/presentation/src/handlers/form/question_handler.rs
- server/presentation/src/handlers/notification_handler.rs
- server/presentation/src/handlers/user_handler.rs
> Json のパースエラーを plain/text ではなく json で返すようにする
