GiganticMinecraft/seichi-portal-backend

rust-toolchain.toml, server/Makefile.common.toml
これでキャッシュキー変わるからCIが復活するはず？
=> 復活した
=> chore(deps): announcing rust 1.68.0

.github/workflows/ci.yaml, rust-toolchain.toml
https://blog.rust-lang.org/2023/04/20/Rust-1.69.0.html
=> Announcing Rust 1.69.0

rust-toolchain.toml
https://blog.rust-lang.org/2023/06/01/Rust-1.70.0.html
=> feat: Announcing Rust 1.70.0

.github/workflows/ci.yaml
nightly を使うと最新すぎて toolchain が利用できない場合があるので、1ヶ月前の nightly を使うことで解決
=> feat: nightly 1 month ago

server/Cargo.lock, server/entrypoint/Cargo.toml
デフォルトで有効になっていた使えるインテグレーションが消えてたのと、いくつか連携できるやつを足した（特にProfiling tracingはないと困るので入れておく）
ref. https://docs.rs/sentry/latest/sentry/#features
ref. https://github.com/GiganticMinecraft/seichi-timed-stats-conifers/blob/master/server/ingestor/Cargo.toml#L14
=> enable sentry features

server/Cargo.lock, server/entrypoint/Cargo.toml, server/entrypoint/src/main.rs
ref: https://crates.io/crates/sentry-tower
ref: https://docs.sentry.io/platforms/rust/performance/instrumentation/automatic-instrumentation/#http-instrumentation
ref: https://github.com/getsentry/symbolicator/blob/master/crates/symbolicator/Cargo.toml
ref: https://github.com/getsentry/symbolicator/blob/master/crates/symbolicator/src/endpoints/mod.rs
=> SentryとTowerを連携する

server/Cargo.lock, server/Cargo.toml, server/common/Cargo.toml, server/common/src/config.rs, server/common/src/lib.rs, server/entrypoint/Cargo.toml, server/entrypoint/src/main.rs, server/presentation/Cargo.toml, server/presentation/src/auth.rs, server/presentation/src/form_handler.rs, server/presentation/src/lib.rs
ユーザー認証(一部)を実装しました。
開発環境でのみBearer tokenを`debug_user`にすることで認証できるようにするために、configの読み取りの実装をcommonに移動しました。
細かいユーザーに関する操作の実装などは、別PRで行います。
=> ユーザー認証(一部)を実装

server/Cargo.lock, server/Cargo.toml, server/Makefile.toml, server/common/Cargo.toml, server/domain/Cargo.toml, server/domain/src/form/models.rs, server/domain/src/repository/form_repository.rs, server/entrypoint/Cargo.toml, server/errors/Cargo.toml, server/errors/src/infra.rs, server/errors/src/lib.rs, server/infra/entities/Cargo.toml, server/infra/outgoing/Cargo.toml, server/infra/outgoing/src/form_outgoing.rs, server/infra/outgoing/src/webhook.rs, server/infra/resource/Cargo.toml, server/infra/resource/src/database/components.rs, server/infra/resource/src/database/form.rs, server/infra/resource/src/dto.rs, server/infra/resource/src/lib.rs, server/infra/resource/src/repository/form_repository_impl.rs, server/migration/Cargo.toml, server/presentation/Cargo.toml, server/presentation/src/form_handler.rs, server/types/Cargo.toml, server/types/src/lib.rs, server/usecase/Cargo.toml, server/usecase/src/form.rs
- form 以外に id を使う前に先回りして `Id<T>` を作っておいた
- builder のアトリビュートを使ったらコードがきれいになった
- anyhow を 使わずに全部 thiserror を使うようにした（エラーハンドリングしたそうなコードがあったため）
- インフラ層は DTO を返すようにした
=> refactor: more clean architecture

server/Cargo.lock, server/Cargo.toml, server/infra/entities/src/sea_orm_active_enums.rs, server/migration/Cargo.toml
#242 , #243 を同時にやらないとコンパイルが通らないので
=> sea-ormとsea-orm-migrationをアップデートする

server/entrypoint/src/main.rs, server/presentation/src/form_handler.rs
API定義では`Location`を返すとなっていたが実際は返していなかった
=> feat: フォーム作成のエントリポイントのレスポンスヘッダにLocationを含める

server/domain/src/user/models.rs, server/infra/resource/src/database/user.rs, server/migration/src/m20220101_000001_create_table.rs, server/presentation/src/auth.rs
やったこと
- `Users` テーブルと `Users`struct にroleを追加する(管理者と一般ユーザーとで分ける)
- 一般ユーザがアクセスできるエンドポイントを列挙して、それ以外で`FORBIDDEN`を返すようにする
=> ユーザーに権限を割り振れるようにする

compose.yaml
Reverts GiganticMinecraft/seichi-portal-backend#322
イメージがなくて起動できなくなっていた
=> Revert "chore(deps): update mysql docker tag to v8.2"

server/Cargo.lock, server/domain/src/repository/form_repository.rs, server/domain/src/user/models.rs, server/entrypoint/src/main.rs, server/infra/resource/src/database/components.rs, server/infra/resource/src/database/form.rs, server/infra/resource/src/repository/form_repository_impl.rs, server/presentation/Cargo.toml, server/presentation/src/auth.rs, server/presentation/src/form_handler.rs, server/usecase/src/form.rs
通常ユーザーがフォームに紐づいた質問を取得する方法がなくなり、新しく取得用のAPIが定義されたので実装しました
=> フォームに紐づいた質問を取得するエンドポイントの実装

server/Cargo.lock, server/domain/src/form/models.rs, server/infra/resource/src/database/form.rs, server/presentation/Cargo.toml, server/presentation/src/form_handler.rs
UUIDは認証情報から、timestampはバックエンド側で生成するようにAPIスキーマが変わったので修正しました。
=> fix: post_answersでUUIDとtimestampを受け取らないようにする

server/infra/resource/src/database/form.rs, server/migration/src/m20220101_000001_create_table.rs
フォームが作成されたときに`default_answer_titles`テーブルにinsertが行われていなかったため、フォームが見つからない判定になってしまうことが原因でした
=> フォームに回答ができない不具合を修正

server/domain/src/user/models.rs
User::AdministratorやStandardUserがそのままシリアライズされるのを修正
ローカルで確認済み
close #348
=> fix serialized string for User

server/infra/resource/src/database/user.rs
close #350
初めてログインしたユーザーの`role`は`insert`されてもいいですが、再ログインユーザーの`role`は`update`されると強制的に`role`のデフォルトである`StandardUser`に上書きれるので、`role`の`update`を行わないようにしました
=> ユーザーがログインしたときにroleがStandardUserに上書きされるのを修正

server/infra/resource/src/database/user.rs
`execute_and_values`を実装したときに置き換え忘れていた
=> refactor: upsert_userのSQL実行でexecute_and_valuesを使うようにする

server/domain/src/form/models.rs, server/infra/resource/src/database/form.rs
=> フォームの公開設定を変更できる機能の実装

docker/Dockerfile
Reverts GiganticMinecraft/seichi-portal-backend#492
cross build で落ちちゃったので
=> Revert "chore(deps): update ubuntu docker tag to v24"

server/errors/src/infra.rs, server/errors/src/lib.rs, server/errors/src/usecase.rs, server/presentation/src/form_handler.rs, server/usecase/src/form.rs
UseCaseで`InfraError`が返されていたのでそれを直す目的と、フロントエンド側でなんのエラーが発生したかを区別できたほうが嬉しいので追加しました
lintが落ちてますが #468 がマージされたら通ると思います
=> UseCaseエラーの追加とエラーレスポンスでエラーコード追加

server/domain/src/form/models.rs, server/infra/resource/src/database/form.rs, server/migration/src/m20220101_000001_create_table.rs, server/presentation/src/form_handler.rs
・API スキーマ側でフォームを更新するときのエンドポイントで、更新する情報は json で受け取るようになったのでそのように更新しました。
・API スキーマ側で `has_response_period` というパラメータも受け取るようになったのでパラメータを更新しました。
・それに合わせて `response_period` を更新する処理の修正を行いました。
#496 を先にマージして、リベースをかけてからマージしてほしいです
=> フォームの情報を更新するときのエンドポイントの実装を修正

server/domain/src/form/models.rs, server/infra/resource/src/repository/form_repository_impl.rs, server/types/src/lib.rs, server/usecase/src/form.rs
普通に `repository` の関数を呼べば十分かつ、`presentation` 層などから `repository` にアクセスすることは不適切なので削除しました
=> refactor: Resolver 関数を廃止

server/domain/src/repository/user_repository.rs, server/entrypoint/src/main.rs, server/infra/resource/src/repository/user_repository_impl.rs, server/presentation/src/handlers/user_handler.rs, server/usecase/src/dto.rs, server/usecase/src/forms/message.rs, server/usecase/src/user.rs
- Discord ID と、ユーザー情報を取得するエンドポイントが分離していたのを一つにまとめる
- 自身のユーザー情報しか確認できなかったのを、他の人の情報も取れるように
=> ユーザー情報を取得するエンドポイントの改善

server/infra/resource/src/database/forms/answer_label.rs, server/infra/resource/src/database/forms/answers.rs, server/infra/resource/src/database/forms/form.rs, server/infra/resource/src/database/forms/form_label.rs, server/infra/resource/src/database/forms/message.rs, server/infra/resource/src/database/forms/question.rs
今までは String から変換しないとランタイムエラーが発生していたが、sea-orm 側に修正 PR を投げてマージされたので修正された
=> refactor: UUID を DB から取得するときに String を経由しない

server/Cargo.lock, server/Cargo.toml, server/errors/Cargo.toml, server/infra/resource/Cargo.toml, server/migration/Cargo.toml
renovate に Cargo.lock だけ更新されるようになったので
=> chore: 依存クレートのバージョンを更新

server/infra/resource/src/database/forms/answers.rs, server/infra/resource/src/database/forms/comment.rs, server/migration/src/m20220101_000001_create_table.rs
=> タイムスタンプを表すカラム名が表記揺れしているのを修正

server/Cargo.lock, server/Cargo.toml, server/migration/Cargo.toml
renovate が Cargo.lock だけ更新し始めたので
=> chore: 使用 crate のバージョンを更新
